language: python
python:
  - "3.7.4"
install:
  - pip install -r requirements.txt
script: python test.py

# deploy:
#   - provider: 
#     username: 
#     password: 
#     site:
#     on:
#       branch: master